version: '3.4'

services:
  catalogdb:
    image: postgres

  basketdb:
    image: postgres

  distributedcache:
    image: redis

  eshop.microservices.catalog.api:
    image: ${DOCKER_REGISTRY-}eshopmicroservicescatalogapi
    build:
      context: .
      dockerfile: Services/Catalog/Eshop.Microservices.Catalog.API/Dockerfile

  eshop.microservices.basket.api:
    image: ${DOCKER_REGISTRY-}eshopmicroservicesbasketapi
    build:
      context: .
      dockerfile: Services/Basket/Eshop.Microservices.Basket.API/Dockerfile

  eshop.microservices.discount.grpc:
    image: ${DOCKER_REGISTRY-}eshopmicroservicesdiscountgrpc
    build:
      context: .
      dockerfile: Services/Discount/Eshop.Microservices.Discount.Grpc/Dockerfile

volumes:
    postgres_catalog:
    postgres_basket:


