version: '3.4'

# services:
#   eshop.microservices.catalog.api:
#     image: ${DOCKER_REGISTRY-}eshopmicroservicescatalogapi
#     build:
#       context: .
#       dockerfile: Services/Catalog/Eshop.Microservices.Catalog.API/Dockerfile

services:
  catalogdb:
    image: postgres


volumes:
    postgres_catalog: