version: '3.4'

services:
  catalogdb:
    image: postgres

  basketdb:
    image: postgres

  distributedcache:
    image: redis

  orderdb:
    image: mcr.microsoft.com/mssql/server

  messagebroker:
    image: rabbitmq:management

  eshop.microservices.catalog.api:
    image: ${DOCKER_REGISTRY-}eshopmicroservicescatalogapi
    build:
      context: .
      dockerfile: Services/Catalog/Eshop.Microservices.Catalog.API/Dockerfile

  eshop.microservices.basket.api:
    image: ${DOCKER_REGISTRY-}eshopmicroservicesbasketapi
    build:
      context: .
      dockerfile: Services/Basket/Eshop.Microservices.Basket.API/Dockerfile

  eshop.microservices.discount.grpc:
    image: ${DOCKER_REGISTRY-}eshopmicroservicesdiscountgrpc
    build:
      context: .
      dockerfile: Services/Discount/Eshop.Microservices.Discount.Grpc/Dockerfile

  eshop.microservices.ordering.api:
    image: ${DOCKER_REGISTRY-}eshopmicroservicesorderingapi
    build:
      context: .
      dockerfile: Services/Ordering/Eshop.Microservices.Ordering.API/Dockerfile

volumes:
    postgres_catalog:
    postgres_basket:



